name = "ShaderAbstractions"
uuid = "65257c39-d410-5151-9873-9b3e5be5013e"
authors = ["SimonDanisch <sdanisch@gmail.com>"]
version = "0.3.1"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
ColorTypes = "0.8, 0.9, 0.10, 0.11"
FixedPointNumbers = "0.6, 0.7, 0.8"
GeometryBasics = "0.4.1"
Observables = "0.2, 0.3, 0.4, 0.5"
StaticArrays = "0.11, 0.12, 1.0"
StructArrays = "0.3.0, 0.4, 0.5, 0.6"
Tables = "0.2, 1"
julia = "1"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "LinearAlgebra"]
